### ISSUE TITLE
启用时：服务器错误

### ISSUE THREAD

**Issue by Arepeater** [zhusaidong/SiteRunningTime#1]
exception 'Typecho_Widget_Exception' with message '无法启用插件' in /home/wwwroot/x.org/var/Widget/Plugins/Edit.php:98
Stack trace:
#0 /home/wwwroot/x.org/var/Widget/Plugins/Edit.php(308): Widget_Plugins_Edit->activate('time')
#1 /home/wwwroot/x.org/var/Widget/Do.php(82): Widget_Plugins_Edit->action()
#2 /home/wwwroot/x.org/var/Typecho/Widget.php(221): Widget_Do->execute()
#3 /home/wwwroot/x.com/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#4 /home/wwwroot/x.org/index.php(23): Typecho_Router::dispatch()
#5 {main}

找到了日志但是看不懂啊，老哥能帮我看下问题在哪吗？

**Comment by zhusaidong** [comment]
启动其它插件会报错吗？

**Comment by zhusaidong** [comment]
你的插件列表里是不是有个`time`的插件

**Comment by Arepeater** [comment]
哇哦，谢谢老哥的提醒，我把你的插件文件夹改成了time，改为  SiteRunningTime，启用成功饿了，谢谢谢谢。

2018-03-19 10:37 GMT+08:00 zhusaidong <notifications@github.com>:

**Comment by zhusaidong** [comment]
感谢您的使用。
